# Generated by Django 3.2.12 on 2022-03-24 18:51

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Главный заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_blue',
            field=models.TextField(blank=True, null=True, verbose_name='Синий заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст основания компании'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='short_desc',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=150, null=True, verbose_name='Короткое описание'),
        ),
    ]
