# Generated by Django 3.2.12 on 2022-03-24 19:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0003_auto_20220324_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('body', wagtail.core.fields.StreamField([('description', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(blank=True, label='Текст', null=True, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True, label='Картинка', null=True, required=False))], label='Преимущество'))], blank=True, null=True, verbose_name='Блок преимуществ')),
            ],
            options={
                'verbose_name': 'Преимущества',
            },
            bases=('wagtailcore.page',),
        ),
    ]
