# Generated by Django 3.2.4 on 2022-03-29 18:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_privilege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Flaming stove'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description_blue',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='short_desc',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(blank=True, label='Текст', null=True, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True, label='Картинка', null=True, required=False))], label='Flaming stove'))], blank=True, null=True, verbose_name='Flaming stove'),
        ),
    ]
