# Generated by Django 3.2.4 on 2022-03-29 18:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220329_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True, label='Картинка', null=True, required=False)), ('svg', wagtailsvg.blocks.SvgChooserBlock(blank=True, label='Логотип', null=True, required=False))]))], blank=True, null=True),
        ),
    ]
